name: Do Copy

on:
  push:
    branches:
      - master

jobs:
  do-copy:
    runs-on: ubuntu-latest
    name: Copy settings
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: data copy
        uses: pal-paul/git-copy@v1.2
        with:
          owner: 'pal-paul'
          repo: 'source-repo'
          token: '${{ secrets.TOKEN }}'
          directory: './data'
          detination_directory : 'setting'