name: Do Copy

on:
  push:
    branches:
      - master

jobs:
  do-copy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    name: Copy settings
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: data copy
        uses: pal-paul/git-copy@v2.2.0
        with:
          owner: "pal-paul"
          repo: "global-files"
          token: "${{ secrets.TOKEN }}"
          branch: "settings"
          pull_message: "Update settings"
          directory: "./data"
          destination_directory: "setting"
          reviewers: "PalashPaul-Ingka"
