name: Do Copy

on:
  push:
    branches:
      - master

jobs:
  do-copy:
    runs-on: ubuntu-latest
    name: Copy settings
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: data copy
        uses: pal-paul/git-copy@v1
        with:
          owner: 'pal-paul'
          repo: 'global-files'
          token: '${{ secrets.TOKEN }}'
          branch: 'settings'
          pull_message: "Update settings"
          directory: './data'
          detination_directory : 'setting'
          reviewers: "palashpaul-ingka"